
대수적 효과
우리는 왜 대수적 효과에 대해서 알아야할까? suspense가 대수적 효과에 영향을 받았다고는 하지만, suspense에 적용된 개념적 모델은 대수적 효과가 아니다.  [Dan Abramov](https://mobile.twitter.com/dan_abramov) 는 단지 영감만 받았다고 말하고있다. 이런 개념이 중요하다고 생각되는건 사람마다 다를것이다. 하지만 알아두면 분명히 도움이 되리라 생각한다.

그럼 이제 대수적 효과에 대해서 설명하자면

먼저 코드를 보자

```jsx
function getName(user) {
  let name = user.name;
  if (name === null) {
    throw new Error('A girl has no name');   }
  return name;
}

function makeFriends(user1, user2) {
  user1.friendNames.add(getName(user2));
  user2.friendNames.add(getName(user1));
}

const arya = { name: null };
const gendry = { name: 'Gendry' };
try {
  makeFriends(arya, gendry);
} catch (err) {
  console.log("Oops, that didn't work out: ", err);}}
```
일반적으로 try catch는 어떻게 동작할까? 분명 makeFriends -> getName에서 에러가 발생하면 catch가 실행될것이다. try catch만으로 중간과정 없이 간편하게 에러핸들링을 할 수 있다.

하지만 try catch에는 큰 문제가 있다. 에러가 한번 발생하면 이어서 진행할 수 없다는 점이다. catch 블록에 도달하고나면, 원래 코드를 이어서 실행할 수 있는 방법이 없다.

하지만 에러가 발생해도, 마법처럼 마지막으로 실행했던 곳으로 돌아가서 다른일을 하고싶다면 대수적효과를 사용하면 된다.

음? 에러가 발생해도, 마법처럼 마지막으로 실행했던 곳으로 되돌아간다고 하면, 떠오르는게 있다. 바로 서스펜스의 동작원리와 비슷하다.

다음은 Suspense Fallback ui가 로딩을 처리하는 과정이다. promise를 throw했을때는 suspense가 이를 확인하고 resolve 될 때까지 fallback UI를 보여주다가 promise가 resolve되면, 다시 throw한 곳으로 되돌아가서 정상적인 컴포넌트 로딩을 처리할 수 있게 되는 것이다.

### 대수적 효과(Algebraic effects)?
그럼 이제 대수적효과에 정확한 뜻에 대해서 알아볼 필요가 있어보인다.

**_Algebraic effects are an approach to computational effects based on a premise that impure behaviour arises from a set of operations_** _such as get & set for mutable store, read & print for interactive input & output, or raise for exceptions. This naturally gives rise to handlers not only of exceptions, but of any other effect, yielding a novel concept that, amongst others, can capture stream redirection, backtracking, co-operative multi-threading, and delimited continuations. — Matija Pretnar_

위 글을 해석하면 "대수적 효과란 exception throw등을 포함하는 연산들의 집합으로부터 순수하지 못한 행위가 발생할 수 있다는 전제를 바탕으로 Computational Effect에 대해 접근하는 방식"이다. 

여기서 대수적은  대수학에서 다루는 대상인 수나 변수, 연산 등에 대한 속성을 나타내는 말이고, Computational Effect는 프로그램의 실행 도중 발생하는 일종의 작업(혹은 연산)으로, 예외처리, 상태 변경, 콜백 등과 같은 작업을 포함한다. 이러한 작업들은 프로그램의 실행 과정에서 외부 환경과의 상호작용을 요구하거나, 프로그램의 상태를 변경시키는 등 부수효과(side effect)를 일으킨다.

함수형 프로그래밍에서 순수함수에 중요성을 강조하는데, 이유는 순수함수가 부수효과를 일으키지 않기 때문이다. 하지만 대부분의 프로젝트는 부수효과(액션)을 일으키는 작업이 필수적이다. 그리고 이런 부수효과를 일으키는 작업을 Computational Effects라고 한다. (함수형 프로그래밍에서도 부수효과를 다루기위해 Monads를 사용하곤한다. Monads도 대수적효과와 관련이 있다고한다.)

즉 정리하자면 대수적 효과란 대수를 사용해서 연산을 수행할 때 순수하지 못한 행위들이일어날 수 있고, 이를 전제로 Computational Effect에 대해 접근하는 방식이라고 이해할 수 있다. 

그렇다면 위에서 말하는 Computational Effect에 대해 접근하는 방식은 무엇일까? 바로 적절한 Effect handler를 사용하는 것이다.

아래는 Dan Abramov가 설명한 가상의 문법인 `perform`, `resume`,  `try-handle`를 사용한 코드다.
```ts
function getName(user) {
	let name = user.name;
	if (name === null) {
	// 2. 여기서 효과를 수행(perform)한다.
	name = perform 'ask_name';
	// 5. 그리고 여기로 돌아온다. (name값은 이제 "Arya Stark"이다.)
	}
	return name;
}

function makeFriends(user1, user2) {
	user1.friendNames.add(getName(user2));
	user2.friendNames.add(getName(user1));
}
``
const arya = { name: null };
const gendry = { name: 'Gendry' };
	try {
	// 1. 함수 실행(try-handle 문에서 먼저 실행)
		makeFriends(arya, gendry);
	} handle (effect) {
	// 3. handler로 점프 한다 (try/catch 처럼)
	if (effect === 'ask_name') {
	// 4. 하지만, (try/catch와는 다르게!) 값을 전달하면서 기존 코드를 이어서 진행할 수 있다
		resume with 'Arya Stark';
	}
}
```
기존의 try-catch와 다른점은 Exception throw를 던지고, Effect handler를 수행함으로써 기존의 로직을 이어서 수행하고, resume 키워드는 효과가 수행된 곳으로 다시 돌아갈 수 있다.


###  무엇(what)과 어떻게(how)
[Dan Abramov](https://mobile.twitter.com/dan_abramov) 는 대수적 효과가 무엇(what)과 어떻게(how)를 분리할 수 있게 도와주는 아주 강력한 도구가 될 수 있다고 말한다. 하지만 위 코드만 봤을때는 무엇(what)과 어떻게(how)를 분리했다는 생각이 들지않는다. 아래코드를 보자.

```jsx
function enumerateFiles(dir) {
  const contents = perform OpenDirectory(dir);
  perform Log('Enumerating files in ', dir);
  for (let file of contents.files) {
    perform HandleFile(file);
	}
	perform Log('Enumerating subdirectories in ', dir);             
	for (let directory of contents.dir) {
	    // 재귀를 사용하거나 효과를 갖는 다른 함수를 호출할 수도 있다
	    enumerateFiles(directory);
	  }
	  perform Log('Done');}
	  }
```

```ts
function enumerateFiles(dir) {
  const contents = perform OpenDirectory(dir);
  perform Log('Enumerating files in ', dir);
  for (let file of contents.files) {
    perform HandleFile(file);
	}
	perform Log('Enumerating subdirectories in ', dir);             
	for (let directory of contents.dir) {
	    // 재귀를 사용하거나 효과를 갖는 다른 함수를 호출할 수도 있다
	    enumerateFiles(directory);
	  }
	  perform Log('Done');}
	  }
```

enumerateFiles 함수에서 perform을 선언하고 해당 함수를 "어떻게"를 명시하는 
코드(try handler)로 감싼다.

```jsx
let files = [];
try {
  enumerateFiles('C:\\');
} handle (effect) {
  if (effect instanceof Log) {
    myLoggingLibrary.log(effect.message);    resume;  } else if (effect instanceof OpenDirectory) {
    myFileSystemImpl.openDir(effect.dirName, (contents) => {      resume with contents;    });  } else if (effect instanceof HandleFile) {
    files.push(effect.fileName);    resume;  }
}
// 파일 배열은 이제 모든 파일을 갖고 있다.
```

위 코드에서보면 보기쉽게 정리하면 다음과 같다.

1. `perform OpenDirectory(dir)` 호출
```jsx
else if (effect instanceof OpenDirectory) {
    myFileSystemImpl.openDir(effect.dirName, (contents) => {      resume with contents;    });
```
2. `perform HandleFile(file);` 호출
```jsx
else if (effect instanceof HandleFile) {
    files.push(effect.fileName);    resume;  }
```
일단 두가지만 적겠다.

위 코드에서는 코드를 감싸는 맥락으로 효과에 대한 구체적인 구현 내용으로부터 프로그램 로직을 분리하고있다. 우리는 단지 `perform`을 호출하기만하고, 실제로 내부적으로 발생하는 효과는 알 필요가없다. 대수적효과는 이렇게 "무엇"을 하는지에만 집중하는 코드를 작성하게 해준다. 물론 가상의 문법때문에 이해가 힘들수는 있지만 단지 개념만을 설명하기 위한 코드기때문에 코드를 완벽하게 이해할 필요는 없다.

#### 그렇다면 suspense는?
아래는 react core team [sebmarkbage ](https://gist.github.com/sebmarkbage/2c7acb6210266045050632ea611aebee) github에 있는 suspense의 예시 코드다.
```ts
_// Infrastructure.js_  
let cache = new Map();  
let pending = new Map();

function fetchTextSync(url) {  
  if (cache.has(url)) {  
    return cache.get(url);  
  }  
  if (pending.has(url)) {  
    throw pending.get(url);  
  }  
  let promise = fetch(url).then(  
    response => response.text()  
  ).then(  
    text => {  
      pending.delete(url);  
      cache.set(url, text);  
    }  
  );  
  pending.set(url, promise);  
  throw promise;  
}

async function runPureTask(task) {  
  for (;;) {  
    try {  
      return task();  
    } catch (x) {  
      if (x instanceof Promise) {  
        await x;  
      } else {  
        throw x;  
      }  
    }  
  }  
}
```
위 코드를 이해해보면 다음과 같다.

fetchTextSync 함수는 url을 인자로 받아서 캐시를 확인해서 만약 캐시에 이미 저장되어있다면 저장된 결과를 반환하고, 저장된게 없다면 fetch를 통해 비동기적으로 response를 가져와 캐시에 저장한 뒤에 반환한다. 만약 해당 url이 pending 상태라면 새롭게 요청을 하지않고 해당 Promise 객체를 throw하여 요청이 완료될때 까지 기다리게 한다.

runPureTask함수는 인자로 받은 task(fetchTextSync)함수를 실행한다. 만약 task함수가 실행중 throw가 발생한다면, 그 throw가 "Promise" 객체라면 다시 시도하고, 그 객체가 Promise가 아니라면 그대로 에러를 throw한다. 또한 해당 함수는 위에서 설명한 handler의 역할을 하고있다. runPureTask는 감싸고있는 fetchTextSync의 SideEffect(throw)를 handler를 사용해서 확인한 뒤에 그 SideEffect가 Promise throw라면 에러가 발생했던 곳으로 되돌려주고있다.

마찬가지로 Dan Abramov가 설명한 가상의 문법인 `perform`, `resume`,  `try-handle`를 사용한 코드에서도 try catch와는 다르게 exception throw가 발생했던 곳으로 다시 되돌아갈 수 있다. 또한 두개의 코드 다 내부구현을 신경쓰지 않아도 된다. 그저 무엇을할지 선언하면된다.


### 끝
간단하게 정리하려고했는데 쓰다보니까 글이 너무 길어졌다.. 여러 글을 읽고 정리했지만 논리적으로 이해하기 힘든 글이 많았다. 내가 볼때는 괜찮지만 내가 쓴 글도 다른사람이 보기에는 똑같을 것 같다.

어려운 부분이 많은데, 위에서 제시한 코드들은 가상의 코드이기 떄문에 코드를 완벽하게 이해할필요는 없다. Suspense가 대수적효과에 어떻게 영향을 받았는지만 이해한다면 충분하다고 생각한다.

- https://overreacted.io/ko/algebraic-effects-for-the-rest-of-us/
- https://yeoulcoding.me/331
- https://maxkim-j.github.io/posts/react-query-preview/
- https://stackoverflow.com/questions/49626714/what-does-algebraic-effects-mean-in-fp